{% set python_min = "3.10" %}
{% set name = "jax" %}
{% set version = "0.5.2" %}

package:
  name: jax
  version: {{ version }}

source:
  # Only pull source after PyPI release
  url: https://pypi.org/packages/source/j/jax/jax-{{ version }}.tar.gz
  sha256: 2aef7d1912df329470c47ce8f2e6521c105e84aa620311494048c391235087c6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.25
    - opt_einsum
    - scipy >=1.11.1
    - ml_dtypes >=0.4.0
    # Minimum should be from _minimum_jaxlib_version in https://github.com/jax-ml/jax/blob/main/jax/version.py
    - jaxlib >=0.5.1,<=0.5.2
    - importlib-metadata >=4.6
  run_constrained:
    # https://github.com/jax-ml/jax/blob/main/jax_plugins/cuda/plugin_setup.py
    - cudnn >=9.2.1.18,<10.0

test:
  imports:
    - jax
    - jax._src
  commands:
    - pip check
  requires:
    - pip
    # Test with the declared minimum jaxlib
    - jaxlib =={{ minimum_jaxlib_version }}
    - python {{ python_min }}

about:
  home: https://github.com/jax-ml/jax
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Differentiate, compile, and transform Numpy code
  dev_url: http://github.com/jax-ml/jax

extra:
  recipe-maintainers:
    - ocefpaf
    - ericmjl
    - ngam
    - ehfd
    - conda-forge/jaxlib
