{% set name = "jax" %}
{% set version = "0.4.8" %}

package:
  name: jax
  version: {{ version }}

source:
  # only pull source after PyPI release.
  url: https://pypi.io/packages/source/j/jax/jax-{{ version }}.tar.gz
  sha256: 08116481f7336db16c24812bfb5e6f9786915f4c2f6ff4028331fa69e7535202

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - numpy >=1.20
    - opt_einsum
    - scipy >=1.5
    - ml_dtypes >=0.0.3
    # Not declared in the metadata but essential to this package.
    # update minimum from https://github.com/google/jax/blob/main/jax/version.py#L21
    - jaxlib >=0.4.7

test:
  imports:
    - jax
    - jax._src
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/google/jax
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Differentiate, compile, and transform Numpy code

extra:
  recipe-maintainers:
    - ocefpaf
    - ericmjl
    - ngam
